# Generated by Django 2.2.4 on 2019-08-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('is_liquid', models.BooleanField(default=False, help_text='is the product a liquid or not?', verbose_name='is liquid')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('address_line_1', models.CharField(max_length=300, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=300, verbose_name='address line 2')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('zip_code', models.CharField(max_length=15, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kg', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price per kilogram')),
                ('price_l', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price per liter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='shopping.Product', verbose_name='product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='shopping.Shop', verbose_name='product')),
            ],
        ),
    ]
