# Generated by Django 2.2.4 on 2019-08-23 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('address_line_1', models.CharField(max_length=300, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=300, verbose_name='address line 2')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('zip_code', models.CharField(max_length=15, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_fruit', models.BooleanField(default=False)),
            ],
            options={
                'index_together': {('name', 'is_fruit')},
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='price per kilogram')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='unit price')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='shopping.Shop', verbose_name='shop')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='shopping.Vegetable', verbose_name='vegetable')),
            ],
        ),
    ]
