# Generated by Django 2.2.4 on 2019-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='price per liter'),
        ),
    ]
