# Generated by Django 2.2.4 on 2019-08-23 15:51

from django.db import migrations

vegetables_list = (
    'Acorn squash', 'Alfalfa', 'Anise', 'Artichoke', 'Arugula', 'Asparagus', 'Aubergine', 'Azuki beans',
    'Banana squash', 'Basil', 'Bean sprouts', 'Beet', 'Beetroot', 'Bell pepper', 'Black beans', 'Black-eyed peas',
    'Bok choy', 'Borlotti bean', 'Broad beans', 'Broccoflower', 'Broccoli', 'Brussels sprouts', 'Butternut squash',
    'Cabbage', 'Calabrese', 'Capsicum', 'Caraway', 'Carrot', 'Carrots', 'Cauliflower', 'Cayenne pepper',
    'Celeriac', 'Celery', 'Chamomile', 'Chard', 'Chickpeas', 'Chili pepper', 'Chives', 'Cilantro', 'Collard greens',
    'Corn', 'Corn salad', 'Courgette', 'Cucumber', 'Daikon', 'Delicata', 'Dill', 'Eggplant', 'Endive',
    'Fennel', 'Fiddleheads', 'Frisee fungus', 'Garlic', 'Gem squash', 'Ginger', 'Grain', 'Green beans',
    'Green onion', 'Green pepper', 'Habanero', 'Herbs', 'Horseradish', 'Hubbard squash', 'Jalapeno',
    'Jerusalem artichoke', 'Jicama', 'Kale', 'Kidney beans', 'Kohlrabi', 'Lavender', 'Leek', 'Legumes', 'Lemon',
    'Grass', 'Lentils', 'Lettuce', 'Lima beans', 'Maize', 'Mangel-wurzel', 'Mangetout', 'Marjoram', 'Marrow',
    'Mung beans', 'Mushrooms', 'Mustard greens', 'Navy beans', 'Nettles', 'New Zealand spinach', 'Okra', 'Onion',
    'Oregano', 'Paprika', 'Parsley', 'Parsley', 'Parsnip', 'Patty pans', 'Peas', 'Peppers', 'Pimento', 'Pinto beans',
    'Plant', 'Potato', 'Pumpkin', 'Purple', 'Salsify', 'Radicchio', 'Radish', 'Red onion', 'Red pepper', 'Rhubarb',
    'Root vegetables', 'Rosemary', 'Runner beans', 'Rutabaga', 'Sage', 'Salsify', 'Scallion', 'Shallot',
    'Skirret', 'Snap peas', 'Soy beans', 'Spaghetti squash', 'Spinach', 'Spring onion', 'Squash',
    'Squashes', 'Swede', 'Sweet potato', 'Sweetcorn', 'Tabasco pepper', 'Taro', 'Tat soi', 'Thyme', 'Tomato',
    'Tubers', 'Turnip', 'Wasabi', 'Water chestnut', 'Watercress', 'White radish', 'Yam', 'Yellow onion', 'Zucchini'
)

fruits_list = (
    'Abiu', 'Acai', 'Acerola', 'Ackee', 'African cherry', 'Orange', 'African cucumber', 'African medlar',
    'African', 'Moringa', 'Agave plant', 'Aizen fruit', 'Alligator apple', 'Amazon grape', 'Ambarella',
    'American black elderberry', 'American chestnut', 'American hazelnut shrub', 'American mayapple',
    'American red raspberry', 'Apple', 'Apricot', 'Aprium', 'Araza', 'Arhat', 'Atemoya', 'Atherton raspberry',
    'Avocado', 'Babaco', 'Bacuri fruit', 'Bael', 'Balsam apple', 'Banana', 'Barbadine', 'Barbados cherry',
    'Barberry', 'Batuan fruit', 'Bayberry', 'Beach plum', 'Bearberry', 'Beechnut', 'Berry', 'Betel nut',
    'Bignay', 'Bilberry', 'Bilimbi', 'Bitter gourd', 'Black apple', 'Black cherry', 'Black mulberry',
    'Black raspberry', 'Black sapote', 'Blackberry', 'Blackcurrant', 'Blood lime', 'Blood orange', 'Blue tongue',
    'Blueberry', 'Bolwarra', 'Bottle gourd', 'Boysenberry', 'Bramble', 'Brazil nut', 'Brazilian Guava', 'Breadfruit',
    'Broadleaf', 'Bramble', 'Brush cherry', 'Buffaloberry', 'Burdekin plum', 'Burmese grape', 'Calabash', 'Calamansi',
    'Calamondins', 'Canistel', 'Cantaloupe', 'Cape gooseberry', 'Capuli cherry',
    'Carob fruit', 'Cashew apple', 'Cedar bay cherry', 'Cempedak', 'Ceylon gooseberry', 'Charichuelo fruit',
    'Chayote fruit', 'Cherimoya fruit', 'Cherry fruit', 'Chokeberry', 'Chokecherry',
    'Citrofortunella', 'Clementines', 'Cloudberry', 'Cluster fig', 'Coco plum', 'Common apple berry',
    'Conkerberry', 'Cornelian cherry', 'Cranberry', 'Crowberry', 'Cucumber', 'Cupuacu', 'Damson', 'Date plum',
    'Davidson’s plum', 'Dead man’s fingers', 'Dekopon', 'Desert fig', 'Desert lime', 'Dodder laurel',
    'Double coconut', 'Dragon fruit', 'Duku fruit', 'Durian', 'Eastern hawthorn', 'Elephant apple',
    'Emu apple', 'Emu berry', 'Fairchild tangerine', 'False mastic', 'Feijoa', 'Fibrous satinash',
    'Finger lime', 'Florida strangler fig', 'Forest strawberries', 'Gac fruit', 'Galia melon',
    'Gambooge', 'Genip', 'Giant granadilla', 'Golden apple', 'Goumi fruit', 'Governor’s plum', 'Granadilla',
    'Grapefruit', 'Grapes', 'Grapple', 'Greengage', 'Ground plum', 'Grumichama', 'Guanabana', 'Guarana',
    'Guavaberry', 'Hackberry', 'Hardy-kiwi', 'Hawthorn', 'Honeydew', 'Honeysuckle', 'Horned melon', 'Huckleberry',
    'Huito', 'Ice cream bean', 'Ilama', 'Illawarra plum', 'Imbe fruit', 'Indian fig', 'Indian gooseberry',
    'Indian prune', 'Indian almond', 'Indian jujube', 'Jabotacaba', 'Jackfruit', 'Jambul fruit', 'Japanese persimmon',
    'Jatoba fruit', 'Jelly palm', 'Jocote', 'Jostaberry', 'Jujube', 'Junglesop',
    'Juniper berry', 'Kabosu fruit', 'Kaffir lime', 'Kahikatea', 'Kakadu plum', 'Kapok', 'Karkalla',
    'Karonda', 'Kei apple', 'Kepel', 'Keule', 'Kiwi', 'Korlan', 'Kumquat', 'Kundong', 'Kutjera', 'Kwai muk',
    'Lablab', 'Lady apple', 'Lakoocha', 'Langsat', 'Lapsi', 'Lardizabala', 'Lemato', 'Lemon aspen', 'Lemons',
    'Leucaena', 'Lillypilly', 'Limeberry', 'Limequat', 'Lingonberry', 'Loganberry', 'Loquat', 'Lucuma', 'Lychee',
    'Ma-praang', 'Macadamia', 'Madrono', 'Malay apple', 'Mamey sapote', 'Mammee apple', 'Mamoncillo',
    'Mandarin', 'Mangaba', 'Mangosteen', 'Manila tamarind', 'Manoao', 'Maqui', 'Marang', 'Marionberry', 'Marula',
    'Mayan nut', 'Mayapple', 'Maypop', 'Melinjo', 'MelonPear', 'Midyim', 'Miracle fruit', 'Mock strawberry',
    'Monstera delicisiosa', 'Mora de Castilla', 'Morinda', 'Mountain soursop', 'Mountain pepper',
    'Muscadine', 'Naartjie', 'Nageia', 'Nance', 'Naranjilla', 'Nectacotum', 'Nectarines', 'Neem', 'Nere', 'Nonda plum',
    'Nungu', 'Nutmeg', 'Oil Palm', 'Olallieberry', 'Olive', 'Orangelo', 'Oranges', 'Oregon grape',
    'Oroblanco', 'Ortanique', 'Otaheite gooseberry', 'Papaya', 'Passion fruit', 'Peach', 'Peach palm',
    'Peanut', 'Pears', 'Pecan', 'Pequi', 'Persian lime', 'Persimmon', 'Peumo', 'Phalsa', 'Physalis fruit',
    'Pigeon pea', 'Pigeon plum', 'Pigface', 'Pili nut', 'Pine apple', 'Pineberry', 'Pink-flowered native raspberry',
    'Plum', 'Plumcot', 'Pluot', 'Pomato', 'Pomegranate', 'Pulasan', 'Pummelo', 'Rambutan',
    'Rangpur', 'Red mombin', 'Riberry', 'Rollinia', 'Rose apple', 'Safou', 'Salak', 'Santol', 'Sapodilla',
    'Soncoya', 'Star apple', 'Star fruit', 'Strawberry guava', 'Sugar apple', 'Sweet orange', 'Sweet pepper',
    'Tamarind', 'Tangelo', 'Tangor', 'Tayberry', 'Tomato', 'Ugli', 'Vanilla', 'Velvet apple', 'Walnut',
    'Watermelon', 'Wax jambu', 'White sapote', 'Youngberry', 'Yuzu'
)


def add_species(apps, _):
    Vegetable = apps.get_model('shopping', 'Vegetable')
    vegetables = [Vegetable(name=vegetable) for vegetable in vegetables_list]
    fruits = [Vegetable(name=fruit, is_fruit=True) for fruit in fruits_list]
    vegetables.extend(fruits)
    Vegetable.objects.bulk_create(vegetables)


def remove_species(apps, _):
    Vegetable = apps.get_model('shopping', 'Vegetable')
    Vegetable.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_species, remove_species)
    ]
