# Generated by Django 2.2.4 on 2019-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190818_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='unit price'),
        ),
    ]
