# Generated by Django 2.2.4 on 2019-08-23 16:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_add_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='provenance',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
