# Generated by Django 2.2.4 on 2019-08-21 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_productlisting_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='price_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='price per kilogram'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='shopping.Shop', verbose_name='shop'),
        ),
    ]
