# Generated by Django 2.2.4 on 2019-08-23 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_productlisting_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
    ]
